version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    
  backend:
    build:
      context: .  # Indica la ruta donde está el Dockerfile del backend
    ports:
      - "8000:8000"  # Exponer el puerto 8000 para FastAPI
    depends_on:
      - db  # El backend depende de la base de datos
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase

volumes:
  postgres_data:
